### ISSUE TITLE
Basic infrastructure

### ISSUE THREAD

**Issue by adamrneary** [adamrneary/restful-etl#1]
- [x] Express
- [x] Mongoose
- [x] Your favorite basic node/mongoose admin (e.g. http://andzdroid.github.io/mongo-express)
- [x] Mocha/chai for unit tests
- [x] supertest (i think!) for testing api
- [ ] Deployed to Nodejitsu (see adam for credentials)

**Comment by adamrneary** [comment]
comments so far:
- I was able to run npm test and npm start
- i was able to access http://activecell.github.io/restful-etl/
- I don't know how to access the mongoose admin
- we still need to deploy to nodejitsu

cc @MarinaPM and @dunice-igort

**Comment by dunice-igort** [comment]
run mongo-express: node node_modules/mongo-express/app

Now start page is not available. This is a known problem and the changes already merged to master, but the npm package not updated. I think we can wait until it is updated and now use the link http://localhost:8081/db/etl.

I'm have some problems with  to deploy to nodejitsu. I can not install npm modules. An error occurs, but I do not know the exact error and I can not fix it. Probably we could use heroku for deployment?
